<?php

namespace DHBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PeliculasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeliculasRepository extends EntityRepository
{
}
