services:
    dh.allNews:
        class: DHBundle\Model\TodasLasNoticias
        arguments: ["@doctrine.orm.entity_manager"]
    dh.theNew:
        class: DHBundle\Model\LaNoticia
        arguments: ["@doctrine.orm.entity_manager"]
