<?php

namespace My\RecipesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * prueba1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class prueba1Repository extends EntityRepository
{
}
