DHBundle\Entity\Noticias:
    type: entity
    table: null
    repositoryClass: DHBundle\Repository\NoticiasRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titulo:
            type: string
            length: 255
        descripcion:
            type: text
            nullable: true
        fecha:
            type: date
        urlImg:
            type: string
            length: 255
            column: url_img
            nullable: true
    lifecycleCallbacks: {  }
